config/routes.rb
MatCore::Application.routes.draw do
  resources :b_categories

  resources :a_categories

end

app/models/a_category.rb
class ACategory < ActiveRecord::Base
  has_many :b_categories
  attr_accessible :display, :name
end

app/models/b_category.rb
class BCategory < ActiveRecord::Base
  belongs_to :a_category
  attr_accessible :display, :name
end

app/controllers/a_categories_controller.rb
class ACategoriesController < ApplicationController
  # GET /a_categories
  # GET /a_categories.json
  def index
    @a_categories = ACategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @a_categories }
    end
  end

  # GET /a_categories/1
  # GET /a_categories/1.json
  def show
    @a_category = ACategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @a_category }
    end
  end

  # GET /a_categories/new
  # GET /a_categories/new.json
  def new
    @a_category = ACategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @a_category }
    end
  end

  # GET /a_categories/1/edit
  def edit
    @a_category = ACategory.find(params[:id])
  end

  # POST /a_categories
  # POST /a_categories.json
  def create
    @a_category = ACategory.new(params[:a_category])

    respond_to do |format|
      if @a_category.save
        format.html { redirect_to @a_category, notice: 'A category was successfully created.' }
        format.json { render json: @a_category, status: :created, location: @a_category }
      else
        format.html { render action: "new" }
        format.json { render json: @a_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /a_categories/1
  # PUT /a_categories/1.json
  def update
    @a_category = ACategory.find(params[:id])

    respond_to do |format|
      if @a_category.update_attributes(params[:a_category])
        format.html { redirect_to @a_category, notice: 'A category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @a_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /a_categories/1
  # DELETE /a_categories/1.json
  def destroy
    @a_category = ACategory.find(params[:id])
    @a_category.destroy

    respond_to do |format|
      format.html { redirect_to a_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/b_categories_controller.rb
class BCategoriesController < ApplicationController
  # GET /b_categories
  # GET /b_categories.json
  def index
    @b_categories = BCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @b_categories }
    end
  end

  # GET /b_categories/1
  # GET /b_categories/1.json
  def show
    @b_category = BCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @b_category }
    end
  end

  # GET /b_categories/new
  # GET /b_categories/new.json
  def new
    @b_category = BCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @b_category }
    end
  end

  # GET /b_categories/1/edit
  def edit
    @b_category = BCategory.find(params[:id])
  end

  # POST /b_categories
  # POST /b_categories.json
  def create
    @b_category = BCategory.new(params[:b_category])

    respond_to do |format|
      if @b_category.save
        format.html { redirect_to @b_category, notice: 'B category was successfully created.' }
        format.json { render json: @b_category, status: :created, location: @b_category }
      else
        format.html { render action: "new" }
        format.json { render json: @b_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /b_categories/1
  # PUT /b_categories/1.json
  def update
    @b_category = BCategory.find(params[:id])

    respond_to do |format|
      if @b_category.update_attributes(params[:b_category])
        format.html { redirect_to @b_category, notice: 'B category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @b_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /b_categories/1
  # DELETE /b_categories/1.json
  def destroy
    @b_category = BCategory.find(params[:id])
    @b_category.destroy

    respond_to do |format|
      format.html { redirect_to b_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/a_categories_helper.rb
module ACategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/b_categories_helper.rb
module BCategoriesHelper
end

app/views/a_categories/_form.html.erb
<%= form_for(@a_category) do |f| %>
  <% if @a_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@a_category.errors.count, "error") %> prohibited this a_category from being saved:</h2>

      <ul>
      <% @a_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display %><br />
    <%= f.number_field :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/a_categories/edit.html.erb
<h1>Editing a_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @a_category %> |
<%= link_to 'Back', a_categories_path %>

app/views/a_categories/index.html.erb
<h1>Listing a_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Display</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @a_categories.each do |a_category| %>
  <tr>
    <td><%= a_category.name %></td>
    <td><%= a_category.display %></td>
    <td><%= link_to 'Show', a_category %></td>
    <td><%= link_to 'Edit', edit_a_category_path(a_category) %></td>
    <td><%= link_to 'Destroy', a_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New A category', new_a_category_path %>

app/views/a_categories/new.html.erb
<h1>New a_category</h1>

<%= render 'form' %>

<%= link_to 'Back', a_categories_path %>

app/views/a_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @a_category.name %>
</p>

<p>
  <b>Display:</b>
  <%= @a_category.display %>
</p>


<%= link_to 'Edit', edit_a_category_path(@a_category) %> |
<%= link_to 'Back', a_categories_path %>

app/views/b_categories/_form.html.erb
<%= form_for(@b_category) do |f| %>
  <% if @b_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@b_category.errors.count, "error") %> prohibited this b_category from being saved:</h2>

      <ul>
      <% @b_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display %><br />
    <%= f.number_field :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/b_categories/edit.html.erb
<h1>Editing b_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @b_category %> |
<%= link_to 'Back', b_categories_path %>

app/views/b_categories/index.html.erb
<h1>Listing b_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Display</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @b_categories.each do |b_category| %>
  <tr>
    <td><%= b_category.name %></td>
    <td><%= b_category.display %></td>
    <td><%= link_to 'Show', b_category %></td>
    <td><%= link_to 'Edit', edit_b_category_path(b_category) %></td>
    <td><%= link_to 'Destroy', b_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New B category', new_b_category_path %>

app/views/b_categories/new.html.erb
<h1>New b_category</h1>

<%= render 'form' %>

<%= link_to 'Back', b_categories_path %>

app/views/b_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @b_category.name %>
</p>

<p>
  <b>Display:</b>
  <%= @b_category.display %>
</p>


<%= link_to 'Edit', edit_b_category_path(@b_category) %> |
<%= link_to 'Back', b_categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MatCore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>